# Package Overview
package_name: model_package

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (anomaly)
target: target

pipeline_name: model_package
pipeline_save_file: anomaly_model_output_v
pipeline_file_name: anomaly_model_output_v_version.pkl

# SageMaker Variables

features:
  - one
  - two
  - three

# set train/test split
test_size: 0.1

# to set the random seed
random_seed: 0

alpha: 0.001

# PCA hyperparameters
pca_components: .99
pca_random_state: 0


# IsoForest hyperparameters
